### ISSUE TITLE
Тимофей задание на стажировку

### ISSUE THREAD

**Issue by Bonuch** [ADCI/frontend-junior-initial-task#1]
Совершенно не могу разобраться с блоком, который должен выезжать снизу. Это последний момент на котором я уже очень долго вишу.

**Comment by DChuchin** [comment]
Не понятно что нужно сделать или что-то не получается? Чем подробней опишешь проблему, тем проще будет тебе помочь

**Comment by Bonuch** [comment]
Я совершенно не понимаю, как сделать так, чтобы блок, который помечен красным, выезжал снизу вверх. Я перерыл кучу инфы в интернете, но видимо не то искал.
--
Отправлено из Mail.ru для Android четверг, 19 августа 2021г., 20:43 +06:00 от Dmitry  ***@***.*** :

**Comment by DChuchin** [comment]
Посмотри на реализацию аккордеона или выпадающего меню. По сути тебе нужно сделать блок который появляется по нажатию на кнопку. А потом уже сделать для него анимацию. Про анимацию на css можно почитать, например, тут https://learn.javascript.ru/css-transitions

**Comment by Bonuch** [comment]
Добрый день! 
Я до сих пор не смог решить вопрос с выезжающим блоком. Но всё остальное у меня уже достаточно давно готово. Могу ли я отправить то что есть и продолжить разбираться с блоком?
--
Отправлено из Mail.ru для Android пятница, 20 августа 2021г., 00:58 +06:00 от Dmitry  ***@***.*** :

**Comment by Back-end-ADCI** [comment]
Лучше отправить законченную работу и не уложиться в срок, чем уложиться и прислать неготовую страницу. Однако в таком случае в сопроводительном письме следует указать причину задержки.

**Comment by Bonuch** [comment]
https://github.com/Bonuch/Internship-in-adci.git

Всё упиралось только лишь в блок, который занял дня 3. Как оказалось, не правильно искал...
